<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Laravel\Sanctum\HasApiTokens;

class Product extends Model implements HasMedia
{
    use HasApiTokens, HasFactory, InteractsWithMedia;

    protected $fillable = [
        'name', 'description', 'price', 'status', 'slug'
    ];

    protected $appends = [
        'image'
    ];

    public function getImageAttribute()
    {
        if($this->getMedia('images')->isNotEmpty()){
            return $this->getMedia('images')[0]->getFullUrl();
        }else {
            return null;
        }
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model) {
            $model->slug = Str::slug($model->name, '-');
        });
    }
}
